name: jpush_flutter
description: JIGUANG officially supported JPush Flutter plugin (Android & iOS). 极光推送官方支持的 Flutter 插件（Android & iOS）(https://www.jiguang.cn).
version: 3.0.0
# author: xudong.rao <xudong.rao@outlook.com>
homepage: https://www.jiguang.cn

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  platform: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.jiguang.jpush
        pluginClass: JPushPlugin
      ios:
        pluginClass: JPushPlugin
